Update openstacksdk version
openstacksdk requirement version needs to be updted from 1.0.1 to
1.0.2 to avoid this error:

ERROR: Cannot install tempest-nfv-plugin==0.0.1.dev672 because these package versions have conflicting dependencies.

The conflict is caused by:
    tempest-nfv-plugin 0.0.1.dev672 depends on openstacksdk===1.0.1
    The user requested (constraint) openstacksdk===1.0.2